WayRoom/urls.py
from django.contrib import admin
from django.urls import path, include
from . import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('djoser.urls')),
    path('auth/', include('djoser.urls.jwt')),
    path('', include('main.urls')),

] 
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *
from WayRoom import settings
from django.conf.urls.static import static

urlpatterns = [
    path('home', home, name='home'),
    path('', RegisterUser.as_view(), name='register'),
    path('login', Authenticate.as_view(), name='login'),
    path('change', change, name='change'),
    path('profile/<int:pk>/', profile, name='profile'),
    path('logout', logout_user, name='logout'),
    path('post_edit/<int:pk>/', post_edit, name='post_edit'),
    path('search_friends', Search.as_view(), name='Search_friends'),
    path('create_post', PostV, name='create_post'),
    path('add_friend', addFriend, name='friend'),
    path('homechat', homechat, name='homechat'),
    path('room/<int:room>/<str:user>/', MessageView, name='room'),
    path('addcomment/<int:pk>/', AddComment.as_view(), name='addcomment'),
    path('post/<int:pk>/', PostDetail.as_view(), name='post_detail'),
    path('team/<int:pk>/', TeamDetail.as_view(), name='team_detail'),
    path('room/<int:pk>/', RoomDetail.as_view(), name='room_detail'),
] 
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.urls import reverse
from users.models import User
from django.utils import timezone
import django

user = get_user_model()

class Post(models.Model):
    title = models.CharField(max_length=100)
    text = models.TextField(null=True, blank=True)
    image = models.ImageField(upload_to='photos/%Y/%m/%d', null=True, blank=True)
    user = models.ForeignKey(User, on_delete=models.DO_NOTHING)
    time = models.DateTimeField(auto_now_add=True)


    def get_absolute_url(self):
        return reverse('post_detail', kwargs={'pk': self.pk})


class Comments(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    text = models.TextField()
    parent = models.ForeignKey('self', on_delete=models.SET_NULL, blank=True, null=True)

    def __str__(self):
        return f'{self.user}-{self.post}'


class Likes(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    is_liked = models.BooleanField(default=False)


class Category(models.Model):
    title = models.CharField(max_length=255)

    def __str__(self):
        return self.title

class Group_Room(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)
    logo = models.ImageField(upload_to='logos/%Y/%m/%d', blank=True, null=True)
    admins = models.ManyToManyField(User, related_name='admins')
    users = models.ManyToManyField(User, related_name='room_users')
    cat = models.ForeignKey(Category, on_delete=models.DO_NOTHING)

    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse('room_detail', kwargs={'pk': self.pk})


class Team(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)
    logo = models.ImageField(upload_to='logos/%Y/%m/%d', blank=True, null=True)
    admins = models.ManyToManyField(User, related_name='team_admins')
    users = models.ManyToManyField(User, related_name='team_users')
    Group_Room = models.ManyToManyField(Group_Room, null=True, blank=True)
    status = models.CharField(max_length=255)
    Stars = models.IntegerField(default=0)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('team_detail', kwargs={'pk': self.pk})

main/forms.py
from django.contrib.auth import get_user_model
from .models import *
from django.forms import forms, ModelForm
from django import forms
from phonenumber_field.formfields import PhoneNumberField

User = get_user_model()


class UserForm(ModelForm):
    class Meta:
        model = User
        fields = ['username', 'phone', 'email', 'password']


    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super(UserForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user



class AuthForm(ModelForm):
    class Meta:
        model = User
        fields = ['username', 'password']


class ChangeForm(forms.Form):
    new_image = forms.ImageField(required=False)
    new_username = forms.CharField(max_length=100)
    new_bio = forms.CharField(widget=forms.Textarea(), required=False)
    new_email = forms.EmailField(required=False)
    new_phone = PhoneNumberField(required=False)


class posteditForm(forms.Form):
    new_title = forms.CharField(max_length=100)
    new_image = forms.ImageField(required=False)
    new_text = forms.CharField(widget=forms.Textarea(), required=False)

class PostF(forms.Form):
    user = forms.CharField(required=False)
    title = forms.CharField(max_length=100)
    text = forms.CharField(widget=forms.Textarea())
    image = forms.ImageField(required=False)

main/views.py
from typing import Any, Dict
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.views import LoginView
from django.db.models.query import QuerySet
from django.forms.models import BaseModelForm
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import CreateView, View, ListView, DetailView
from .forms import *
from django.contrib.auth import get_user_model, login, logout
from django.contrib.auth import authenticate
from .models import *
import json
from chatapp.models import *
from django.db.models import Q

from users.models import User as USER


class RegisterUser(CreateView):
    form_class = UserForm
    template_name = 'main/register.html'

    def get_success_url(self):
        return reverse_lazy('login')
    
    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect('home')



class Authenticate(LoginView):
    form_class = AuthenticationForm
    template_name = 'main/login.html'

    def get_success_url(self):
        return reverse_lazy('home')


def home(request):
    username = request.user.username
    friends = User.objects.filter(friends = request.user)
    a = []
    for i in friends:
        a.append(i.pk)
    posts = []
    for i in a:
        x = Post.objects.filter(user=i)
        for c in x:
            posts.append(c)

    
    if request.POST.get('check'):
        print(request.POST)
        name = request.POST.get('name')

    teams = Team.objects.filter(users=request.user)

    context = {
        'ischeked': request.POST.get('check'),
        'posts': posts,
        'username': username,
        'title': 'home',
        'teams': teams
    }
        

    return render(request, 'main/index.html', context=context)


def post_edit(request, pk):
    form = posteditForm(request.POST)
    post = Post.objects.get(pk=pk)

    if form.is_valid():
        post.title = form.cleaned_data.get('new_title') if form.cleaned_data.get('new_title') else post.title
        post.title = form.cleaned_data.get('new_image') if form.cleaned_data.get('new_image') else post.title
        post.title = form.cleaned_data.get('new_text') if form.cleaned_data.get('new_text') else post.title
        post.save()
         
        return redirect('home')

 
    context = {
            'form': form,
            'post': post
        }

    return render(request, 'main/postedit.html', context=context)




def change(request):
    form = ChangeForm(request.POST, request.FILES)

    if form.is_valid():
        username = request.user.username
        bio = request.user.bio
        email = request.user.email
        phone = request.user.phone
        new_username = form.cleaned_data.get('new_username')
        new_bio = form.cleaned_data.get('new_bio')
        new_email = form.cleaned_data.get('new_email')
        new_phone = form.cleaned_data.get('new_phone')
        user = User.objects.get(username=username)
        user.image = request.FILES.get('new_image') if request.FILES.get('new_image') else user.image
        user.username = new_username if new_username else user.username
        user.bio = new_bio if new_bio else user.bio
        user.email = new_email if new_email else user.email
        user.phone = new_phone if new_phone else user.phone
        user.save()

        return redirect('home')

    return render(request, 'main/profileedit.html', {'form': form})


def profile(request, pk):
    user = USER.objects.get(pk=pk)
    posts = Post.objects.filter(user=user)
    friends = USER.objects.filter(friends=user)
    context = {
        'friends': friends,
        'posts': posts,
        'user': user,
        'title': profile,
        'username': request.user.username,
        'teams': Team.objects.filter(users=request.user),
    }
    return render(request, 'main/profile.html', context=context)


def logout_user(requset):
    logout(requset)
    return redirect('login')


class Search(ListView):
    model = USER
    template_name = 'main/friends_search.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        a = USER.objects.exclude(friends = self.request.user).values()
        context['qs_json'] = json.dumps(list(a), default=str)
        context['pos'] = self.request.POST
        return context
    

def PostV(request):
      form = PostF(request.POST, request.FILES)
      context = {
          'user': request.user,
          'title': request.POST.get('title'),
          'text': request.POST.get('text'),
          'image': request.FILES.get('image')
      }
      form = PostF(context)
      if form.is_valid():
        post = Post(title=context['title'], text=context['text'], user=context['user'], image = context['image'] if context['image'] else None)
        post.save()
        return redirect('home')
      return render(request, 'main/createpost.html', {'form': form})


def addFriend(request):

    a = request.POST.get('username')
    if a != '':
        user = request.user
        user2 = USER.objects.get(username=a)
        user.friends.add(user2)
        user2.friends.add(user)
        return redirect('home')

    return render(request, 'main/friends_search.html', {'pos': a})


# def homechat(request):
#     if request.method == 'POST':
#         try:
#             get_room = Room.get(user1=request.user)
#             return redirect('room', room='test')
        
#         except Room.DoesNotExist:
#             new_room = Room.objects.create(room_name = 'room', user1=request.user, user2=request.POST.get('name'))
#             new_room.save()
#             return redirect('room', room=new_room.room_name)
#     a = request.POST.get('name')
#     if a:
#         return render(request, 'main/login.html')

#     return render(request, 'main/login.html')

def homechat(request):
    if request.method == 'POST':
        username = list(request.POST)[1]
        other_user = User.objects.get(username=username)
        current_user = request.user

        rooms = Room.objects.filter((Q(user1 = other_user) & Q(user2 = current_user)) | (Q(user1=current_user) & Q(user2 = other_user)))
        if rooms.exists():
            room = rooms.first()
            return redirect('room', room=room.pk, user=other_user)
        else:
            room = Room.objects.create(room_name='room', user1=current_user, user2=other_user)
            room.save()
            return redirect('room', room=room.pk, user=other_user)
    return render(request, 'chatapp/index.html')



def MessageView(request, room, user):
    username = request.user.username

    room = Room.objects.get(pk=room)
    if request.method == 'POST':
        message = request.POST['message']
        print(message)
        new_message = Message(room=room, sender=username, message=message)
        new_message.save()

    get_messages = Message.objects.filter(room=room)
    
    context = {
        "messages": get_messages,
        "user": username,
        'reciever': user
    }
    return render(request, 'chatapp/message.html', context=context)


class AddComment(View):
    def post(self, request, pk):
        context = {
            'user': request.user,
            'post': pk,
            'text': request.POST.get('comment-text')
        }
        if context:
            comm = Comments(user=context['user'], post_id=context['post'], text=context['text'])
            comm.save()

        return redirect('home')



class PostDetail(DetailView):
    model = Post
    template_name = 'main/post_detail.html'
    context_object_name = 'post'


class TeamDetail(DetailView):
    model = Team
    template_name = 'main/team_home.html'
    context_object_name = 'Team'

    def get_context_data(self, **kwargs: Any):
        context = super().get_context_data(**kwargs)
        context['teams'] = Team.objects.filter(users=self.request.user)
        context['username'] = self.request.user.username
        return context


class RoomDetail(DetailView):
    model = Group_Room
    template_name = 'main/room_detail.html'
    context_object_name = 'Room'

    def get_context_data(self, **kwargs: Any):
        context = super().get_context_data(**kwargs)
        context['teams'] = Team.objects.filter(users=self.request.user)
        context['username'] = self.request.user.username
        return context

main/templates/main/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'main/css/main.css' %}">
    <title>{{title}}</title>
</head>
<body>
    <div class="header">
        <div class="logo">
            <div class="img">
                <a href="{% url 'home' %}"><img src="{% static 'main/img/logo.png' %}" alt="WR" class="logophoto"></a>
            </div>
            <div class="title">
                <h1 translate="no">WRoom</a>
            </div>
            
        </div>
        <div class="User">
            {% if request.user.is_authenticated %}
                {% if user.image %}
                <img src="{{user.image.url}}" alt="" class="prof_post_img">
                {% endif %}
                <a href="{% url 'profile' pk=user.pk %}" class="username_head">{{username}}</a>
            {% else %}
                <a href="{% url 'register' %}">Регистрация</a> | <a href="{% url 'login' %}">Войти</a>
            {% endif %}
        </div>
        
        
    </div>

    <aside class="aside">
        <div class="aside_item">
            <img src="{% static 'main/img/home.png' %}" alt="" class="icon"><a href="{% url 'home' %}" class="aside_a">Home</a>
        </div>
        <div class="aside_item">
            <img src="{% static 'main/img/addpost.png' %}" alt="" class="icon"><a href="{% url 'create_post' %}" class="aside_a">Create Post</a>
        </div>
        <div class="aside_item">
            <img src="{% static 'main/img/find_friends.png' %}" alt="" class="icon"><a href="{% url 'Search_friends' %}" class="aside_a">Find friends</a>
        </div>
        <div class="aside_item">
            <img src="{% static 'main/img/profile.png' %}" alt="" class="icon"><a href="{% url 'profile' pk=user.pk %}" class="aside_a">Profile</a>
        </div>
        <div class="aside_item">
            <img src="{% static 'main/img/logout.png' %}" alt="" class="icon"><a href="{% url 'logout' %}" class="aside_a">LogOut</a>
        </div>
    </aside>


    <div class="Teams">
        <div class="teams_title">
            <h3>Teams</h3>
        </div>
        <div class="Teams_items">
            {% for i in teams %}
            {% if forloop.counter <= 7 %}
            <a href="{{i.get_absolute_url}}">{{i.title}}</a>
            {% else %}
            <div class="others_friends">
                <a href="#">Others...</a>
            </div>
            {% endif %}
            {% endfor %}
        </div>
    </div>

    <main>
        {% block content %}
        {% endblock %}
    </main>
    
</body>
</html>

main/templates/main/createpost.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Document</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'main/css/main.css' %}">
</head>
<body>
    <h1 class="new_post">New Post</h1>
    <div class="addpost">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% for i in form %}
            <div class="form-post">
                {{i}}
                {% if i.name != 'user' %}
                {% endif %}
            </div>
            {% endfor %}
            <button type="submit" class="create">Create</button>
        </form>
    </div>


<script>
    document.getElementById('id_user').remove()

    document.getElementById('id_title').classList.add('add_title');
    document.getElementById('id_text').classList.add('add_text');
    document.getElementById('id_image').classList.add('add_image');

    const title = document.getElementById('id_title');
    title.placeholder = 'title';

    const text =document.getElementById('id_text');
    text.placeholder = 'text';
</script>
</body>
</html>

main/templates/main/friends_search.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'main/css/main.css' %}">
    <title>Document</title>
</head>
<body>
    <div class="box">
        <form name="search" action="{% url 'Search_friends' %}" class="search_box">
            {% csrf_token %}
            {% csrf_token %}
            <input type="text" class="input" name="txt" onmouseout="this.value = ''; this.blur();" placeholder="" id="search">
            
        </form>
        <i class="fas fa-search"></i>
        <form action="{% url 'friend' %}" method="post" name="sac">
            {% csrf_token %}
            <div id="boxx">
                <input type="hidden" id="username" name="username">
            </div>
        </form>
        
    
    
    </div>
    <script>
        var input = document.getElementById('search').addEventListener('keyup', (search))
        function search() {
            var input, filter, txtValue;

            filter = document.getElementById('search').value.toLowerCase();
            const data = '{{qs_json}}'

            const rdata = JSON.parse(data.replace(/&quot;/g, '"'))

            if (filter != '') {
                for (i = 0; i < rdata.length; i++) {
                    item = rdata[i]
                    console.log(item)
                    txtValue = item['username'];

                    if (txtValue.indexOf(filter) > -1) {
                        let div = document.createElement('div')
                        document.getElementById('username').value = txtValue
                        div.innerHTML = `<img src='/media/${item['image']}' class='search_img' alt=' '></img><h3>${txtValue}</h3><button class='search_btn' value=${txtValue} name=${txtValue} onclick=add(this) ></button>`
                        div.classList.add('search_div')

                        boxx.append(div)
                    }
                }
            }
        }
        a = '{{pos}}'

        console.log(a)

        function add(el) {
            a = el.value
            document.getElementById('username').value = a
        }
    
    </script>
</body>
</html>

main/templates/main/index.html
{% extends 'main/base.html' %}

{% block content %}

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js" integrity="sha512-894YE6QWD5I59HgZOGReFYm4dnWc1Qt5NtvYSaNcOP+u1T9qYdvdihz0PPSiiqn/+/3e7Jo4EaG7TubfWGUrMQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
{% load static %}
<div class="sear">
    <label for="search" class="search_label"><img src="{% static 'main/img/lupa.png' %}" alt="" class="label_img"></label>
    <input type="search" placeholder="search" class="search">
</div>

{% for i in posts %}
<div class="list_area">  
    <div class="post">
        <div class="prof">
            <div class="profile_img">
                {% if i.user.image %}
                <a href=
                ""><img src="{{i.user.image.url}}" alt="" class="prof_post_img"></a>
                {% endif %}
            </div>
            <div class="profile_username">
                <h4 class="prof_username"><a href="{% url 'profile' pk=i.user.pk %}">{{i.user.username}}</a></h4>
            </div>
            <div class="date">
                <p>{{i.time|date:"M d" }}</p>
            </div>
            
        </div>
        <div>
            <h1 class="post_title">{{i.title}}</h1>
        </div>
        {% if i.image %}
        <div class="post_img">
                <img src="{{i.image.url}}" alt="" class="post_img">
        </div>
        {% endif %}
        <div class="post_other">
            <div class="post_text">
                {{i.text}}
            </div>
        </div>
        <!-- <div class="comments">
            <form action="{% url 'addcomment' pk=i.pk %}" method="post">
                {% csrf_token %}
                <input type="hidden" value="{{i}}">
                <label for="text">cooment</label>
                <textarea name="comment-text" id="text" cols="30" rows="10"></textarea>
                <button type="submit">Send</button>
            </form>

            {% for com in i.comments_set.all %}
            {{com.user}}
            {{com.text}}
            {% endfor %}
            {% load static %}
            
            <form action="" method="post" id="like" name="{{i.pk}}">
                <input type="checkbox" id="ch" name="{{i.pk}}" class="inputForName">
            </form>
        </div> -->
    </div>
</div>



{% endfor %}

<script src="{% static 'main/js/like.js' %}"></script>
{% endblock %}

main/templates/main/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'main/css/reg.css' %}">
    <title>Login</title>
</head>
<body>
    <div class="register">
        <div class="form_title">
            <h1>LogIn</h1>
        </div>
        {% if form.errors %}
                {{form.errors.error}}
        {% endif %}
        <form method="post" class="form" action="{% url 'login' %}">
            {% csrf_token %}
            <!-- {{form.as_p}} -->
            {% for item in form %}
            <div class="form_group">
                {{item}}
                <div class="form_label" id="username">{{item.name}}</div>
            </div>
            {% endfor %}
            <button type="submit" class="form_btn">Войти</button>

            
        </form>
    </div>
    {{a}}
    {{b}}
    <script>
        document.getElementById('id_username').classList.add('form_input')
        document.getElementById('id_password').classList.add('form_input')
    </script>
</body>
</html>

main/templates/main/post_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {{post.title}}
</body>
</html>

main/templates/main/postedit.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'main/css/main.css' %}">
    <title>Document</title>
</head>
<body onload="check()">
    <form action="" method="post">
        {% csrf_token %}
        {% for item in form %}
        <input type="hidden" value="{{post.title}}" id="title">
        <div class="it">{{item}}</div>
        {% endfor %}
        <button type="submit">change</button>
    </form>

    <script>
        function check() {
            let a = document.getElementsByClassName('errorlist');
            for (let el of a) {
                el.remove()
            }

            new_title = document.getElementById('id_new_title');
            title = document.getElementById('title');
            if (!new_title.value) {
                new_title.value = title.value;
            }

        }
    </script>
</body>
</html>

main/templates/main/profile.html
{% extends 'main/base.html' %}
{% load static %}

{% block content %}
<div class="profile">
    <div class="profile_head">
        {% if user.image %}
        <p><img src="{{ user.image.url }}" alt="Hello" class="profile-img"></p>
        {% endif %}
        <img src="{% static 'main/img/dots.png' %}" alt="" class="dots" id="dots" onclick="hid()">
        <div class="hidden_a" id="hidden_a">
            <a href="{% url 'logout' %}" class="logout_btn">LogOut</a>
            <a href="{% url 'change' %}" class="change_btn">Edit</a>
        </div>
    </div>
    
    <div class="username">
        <h1 class="username">{{user.username}}</h1>
    </div>
    
    <div class="profile-items">
        <p class="item-bio">{{user.bio}}</p>
        <h3 class="item-email">{{user.email}}</h3>
        <h3 class="item-phone">{{user.phone}}</h3>
    </div>
    <!-- <a href="{% url 'change' %}" class="change_btn">Edit</a>
    <div class="logout">
        <a href="{% url 'logout' %}" class="logout_btn">LogOut</a>
    </div> -->
</div>

<div class="best_friends">
    <div class="best_title">
        <img src="{% static 'main/img/column.png' %}" alt="" class="column">
        <h1>Best Friends</h1>
        <img src="{% static 'main/img/column.png' %}" alt="" class="column">
    </div>

    <div class="best_friend">
        <ul>
            <li>Sasha</li>
            <li>Artem</li>
            <li>Zaur</li>
        </ul>
    </div>
</div>

<div class="friends">
    <h1>Friends</h1>
    <form action="{% url 'homechat' %}" method="post" name="aaaa">
        {% csrf_token %}
        {% for i in friends %}
        <div class="friend">
            {% if forloop.counter <= 5 %}
            <button type="submit" name="{{i}}" class="friend_btn">{{i}}</button>
            {% else %}
            <div class="others_friends">
                <a href="#">Others...</a>
            </div>
            {% endif %}
        </div>
        
        {% endfor %}
    </form>
    
</div>


<!-- <div class="posts">
    {% for post in posts %}
    <div class="list_area">
        <div class="post">
            <div class="post_title">
                {{post.title}}
            </div>
            {% if post.image %}
            <a href=""><img src="{{post.image.url}}" alt="" class="post_img"></a>
            {% endif %}
            {{post.text}}
            <div class="edit_btn">
                <a href="{% url 'post_edit' pk=post.pk %}" class="change_btn">Edit</a>
            </div>
        </div> 
    </div>
    {% endfor %}
</div> -->


<div class="profile_post_area">
    {% for post in posts %}
    <a href="{{ post.get_absolute_url }}">
        <div class="profile_post">
            <div class="profile_post_title">
                <h4>{{post.title}}</h4>
            </div>
            <div class="profile_post_img">
                {% if post.image %}
                <img src="{{post.image.url}}" alt="" class="profile_post_img">
                {% else %}
                <p class="post_text">{{post.text|truncatechars:50}}...</p>
                {% endif %}
            </div>
            <div class="profile_post_date">
                <h4>{{post.time|date:"M d"}}</h4>
            </div>
        </div>
    </a>
    {% endfor %}
</div>


<script>
    function hid() {
        var a = document.getElementById('hidden_a');
        if (a.style.display == 'block') {
            a.style.display = 'none';
        }
        else {
            a.style.display = 'block';
        }
    }
    
</script>
{% endblock %}

main/templates/main/room_detail.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'main/css/main.css' %}">
</head>
<body>
    <div class="header">
        <div class="logo">
            <div class="img">
                <a href="{% url 'home' %}"><img src="{% static 'main/img/logo.png' %}" alt="WR" class="logophoto"></a>
            </div>
            <div class="title">
                <h1 translate="no">WRoom</a>
            </div>
            
        </div>
        <div class="User">
            {% if request.user.is_authenticated %}
                {% if user.image %}
                <img src="{{user.image.url}}" alt="" class="prof_post_img">
                {% endif %}
                <a href="{% url 'profile' pk=user.pk %}" class="username_head">{{username}}</a>
            {% else %}
                <a href="{% url 'register' %}">Регистрация</a> | <a href="{% url 'login' %}">Войти</a>
            {% endif %}
        </div>
        
        
    </div>




    <div class="ROOM">
        <div class="Room">
            <div class="room_logo">
                {% if Room.logo %}
                <img src="{{Room.logo.url}}" alt="" class="logo_img">
                {% endif %}
            </div>
    
            <h1 class="room_title">{{Room.title}}</h1>
    
            <div class="room_description">
                <h5 class="room_description_txt">{{Room.description}}</h5>
            </div>
    
            <div class="room_admins">
                {% for i in Room.admins.all %}
                <h3 class="admin">{{i}}</h3>
                {% endfor %}
            </div>
    
            <div class="room_users">
                {% for i in Room.team_set.all %}
                <h4 class="user"><a href="{{i.get_absolute_url}}">{{i}}</a></h4>
                {% endfor %}
    
            </div>
        </div>
    
        <div class="Teams_list">
            <h2>Teams</h2>
            <div class="room_users">
                {% for i in Room.team_set.all %}
                <h4 class="user"><a href="{{i.get_absolute_url}}">{{i}}</a></h4>
                {% endfor %}
            </div>
        </div>
    </div>
</body>
</html>